### ISSUE TITLE
Create Figma designs for the UI and flow of the app

### ISSUE THREAD

**Issue by u22633601** [COS301-SE-2024/Culinary-Companion#4]

**Comment by Janicke01** [comment]
Desktop version for design idea of the website
https://www.figma.com/design/arOZQVX3lf29HQ8i4AX62q/Culinary-Companion-Wireframe?node-id=0-1&t=UtuRimilGbmd6hYZ-1

**Comment by Juliaaaa02** [comment]
Mobile version of the design:
https://www.figma.com/design/fgKztaHY6pJPuVxeWeANe5/Culinary-Companion---App-view?node-id=16-1369&t=7IaiSrUZalsWwqXy-1

**Comment by u22633601** [comment]
Just a few suggestions:

Home page:
-have more info on cards
-say how many ingredients I don’t have in my pantry or appliances


Shopping list? Integrate with 60 60, add a button for that 

Pantry add quantity

How does the saved recipes page look, there is a tab for it

Login/ signup, what is everything that a user needs to tell us

Recipe page, 
-the ingredients and stuff aren’t that clear
-I need to be able to say I don’t have this item and see substitutions
-add appliances I would need and be able to see alternatives

Add a page to search in more detail for recipes, based on:
-I have all the ingredients
-type of food(breakfast, dinner, dessert)
-type of cuisine(Indian, Mexican)
-includes this ingredient
-name of ingredient

Add a section for appliances I have and check that against the recipes.
